### ISSUE TITLE
[Feature request] cps and/or setcps in mini-tidal?

### ISSUE THREAD

**Issue by tedthetrumpet** [dktr0/estuary#123]
Would it be possible to support `cps` and/or `setcps` in mini-tidal? Changes of tempo are quite important for the gamelan music we are trying to code, and the set tempo box is not ideal.

**Comment by dktr0** [comment]
This is not possible without a huge change to how MiniTidal works. Right now what you enter in MiniTidal is parsed as a single Tidal ControlPattern - this is why there is no d1, d2, etc. Parsing other or multiple things would be a big change to MiniTidal - it's one I've thought about for some time, but because of how big it is have hesitated on committing to the cost of implementing it. Perhaps you could explain more about how you need tempo changes to work though, so we couild think through some options (including this one)?

**Comment by tedthetrumpet** [comment]
Ok! Didn't realise it would be so fundamental. In Javanese gamelan, a common articulatory structure is two gradually slow down to roughly half the speed, while doubling the density of the patterns played, or vice versa. It's no big deal though, we were sort of doing something like that last night by just repeatedly entering new tempos.

**Comment by dktr0** [comment]
Interesting, we used to do a lot of gradual tempo changes in the early years of the Cybernetic Orchestra too, but it is not so easy with the current state of Estuary. I'm going to reopen this issue as a way to keep this conversation going and visible. I am thinking, for example, that this could be resolved by supporting gradual tempo changes in a fundamental way in Estuary. What would be nice about that would be that it would then be supporting all languages in Estuary, not just Tidal.

**Comment by dktr0** [comment]
Closing for now - since we now have !setcps and !setbpm in the estuary terminal. eg:
```
!setcps 0.6
!setbpm 160
```
