### ISSUE TITLE
documentation, design?

### ISSUE THREAD

**Issue by jwaldmann** [dktr0/estuary#159]
Hi. 

I was researching (academic) information about Estuary (for citing it in my Computer Music lecture) and I found Ogborn, D., Beverley, J., Del Angel, L., Tsabary, E., & McLean, A. (2017). Estuary: Browser-based Collaborative Projectional Live Coding of Musical Patterns. Third International Conference on Live Coding.Available from http://iclc.livecodenetwork.org/2017/cameraReady/ICLC_2017_paper_78.pdf
(cited on https://www.concordia.ca/finearts/music/faculty.html?fpid=eldad-tsabary , that's just the first answer of the seach machine) perhaps you could add (a link to) this paper somewhere (README of this repo, or https://estuary.mcmaster.ca/ )

What is the relation to mini-tidal?  I don't quite see it  the paper, but am I right in assuming that you don't want to give  users access to a real ghci session in their browser, so you've written an interpreter for: Tidal's mini language (in full) plus some subset of Haskell? what subset exactly? Is this solving the same problem https://github.com/jwaldmann/safe-tidal-cli ? I'm not suggesting my package is better - I just want to understand use cases and design choices. E.g., I need the full GHC API at runtime. 

- J.

**Comment by dktr0** [comment]
Hi J,

You're right, we should mention the papers connected to Estuary in more places. One more thing on the to do list... There hasn't really been a paper dealing with the last three years of Estuary developments from a general perspective. Hard to find the time to write with all the other things to do and hacking on the platform itself being so much more gratifying!...

MiniTidal was originally made for Estuary, and indeed, to my knowledge has not been used outside Estuary yet. It used to be part of the Estuary code base but since it might be used for other things I proposed moving it to the Tidal codebase as tidal-parse instead, which has worked out well I think.

I don't think it's really addressing the same question as your package. In Estuary all the rendering is necessarily done client-side, and the client needs to be as lightweight as possible and as performant as possible, given that any individual client could be rendering dozens of live coding programs from multiple different live coding languages. I'm not sure if one could get the whole GHC api running in the browser - certainly when we started Estuary one couldn't - but even if one could now, I don't think we'd want to for the weight and performance considerations. Scalability/performance considerations exist at the server side as well - our current model means all the server is doing is mediating editing, ensemble relations, providing the client and soundfiles, etc and in this way one server can potentially serve many hundreds of ensembles and many thousands of users simultaneously. 

Another way of looking at this to think that Estuary's goal is not to make Tidal "fully" available - rather, it is to make live coding in multiple languages as quickly accessible to people in collaborative settings to as many people as possible. So in that setting the partial availability of some Haskell idioms is definitely an acceptable cost for the other benefits it brings. While there may not have been an updated paper in a while, I talk about the evolution of Estuary and it's philosophy a bit in the talk during the recent Estuary birthday stream (around 6:41:00 here https://www.youtube.com/watch?v=fd83R6gTgxY&t=14341s)

Thanks for reaching out - happy to talk more!

-D

________________________________________

**Comment by jwaldmann** [comment]
Hi, thanks for responding.  I also re-read section 3 (Implementation) of your ICLC 2017 paper. Now I now see this more clearly.  To summarize my understanding:

Estuary: 
* evaluation of expressions in the browser (using a custom parser and interpreter, written in Haskell, compiled to JS)
* fancy editor (not just text - has GUI elements for structure editing)
* audio synthesis also in the browser (webdirt)

So, it's a fully distributed system (the only shared ressource is the contents of the editor buffer) and participants experience the "same" music  since they all run identical client software. Does the editor know about current state of evaluation, e.g., can it highlight source points for currently playing events?

For comparison, flok + safe-tidal-cli 
* plain text editor in the browser (no evaluation)
* evaluation and sound synthesis via separate client program (e.g., safe-tidal-cli, using full ghc but hiding it somewhat)

Editor state is synchronized as well. Participant hears music if they run their own evaluation/synthesis client locally (more risky as everyone needs identical local installation of full tool chain) - or they connect to the output of one such client programm running at a central location (that's what I am currently doing).

**Comment by dktr0** [comment]
Yes, that sounds about right. In answer to the question of the editor "knowing" about evaluation state - that information is certainly "within reach" - however we aren't using it for much of anything yet.

**Comment by jwaldmann** [comment]
Thanks, I used the above info in a lecture today. Feel free to close this issue.

**Comment by dktr0** [comment]
Nice - thanks for reaching out!
