### ISSUE TITLE
Error when running "make fullBuild"

### ISSUE THREAD

**Issue by magfoto** [dktr0/estuary#222]
Following the instructions of the BUILDING.md local installation of Estuary, get the following error when the "make fullBuild" command is executed in terminal on (MacBook Pro w/Ventura):

error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override

This was the error found in the nix log.

**Comment by dktr0** [comment]
Sorry for the delayed reply... not sure what this is at first glance but wonder if different versions of nix make a difference. What version are you using? I am currently mostly building with nix 2.7.0 (on Debian).

**Comment by dktr0** [comment]
(Naturally, I am also curious why you are building Estuary - since people mostly just use the "official" home server at estuary.mcmaster.ca)

**Comment by magfoto** [comment]
Wanted to explore the process of creating a custom theme for a live coding ensemble of 4 local artists.



On Mar 22, 2023, at 1:24 PM, David Ogborn ***@***.***> wrote:



(Naturally, I am also curious why you are building Estuary - since people mostly just use the "official" home server at estuary.mcmaster.ca)

**Comment by dktr0** [comment]
Cool! A few notes about ways to do that without building Estuary:

-to try out changes on the fly, you can use Chrome's inspector (right-click anywhere and choose inspect), click on specific elements to display the style rules they are using, and then navigate through that to find the part near the bottom where it says :root or to other parts where the source comes from one of Estuary's custom stylesheets and make changes. This is useful for figuring out what you want quickly.

-when you know what you want, you can make a new custom stylesheet following the template of (for example) classic.css and then host it somewhere else on the web (for example, a github pages site).

-then you can use that theme by passing a parameter when you load Estuary (this feature has been there for a long time, but undocumented! :) :
```https://estuary.mcmaster.ca?theme=https://dktr0.github.io/estuary-themes/test.css```

-or you can use the new terminal command I just added in Estuary's terminal:
```!theme "https://dktr0.github.io/estuary-themes/test.css"```

I plan to eventually make references to custom themes a feature of ensembles instead of simply client-local settings, but this might be a little while coming. 

Hope that helps! It'll sure be easier than building Estuary which can be a bit of a pain...

**Comment by magfoto** [comment]
This is great!  Thanks David, this should do the trick!


Marcus A. Gordon, PhD Candidate
Joint Program in Digital Media
Department of Computational Arts / York University

***@***.***
http://magfoto.xyz
-----------------------------------------------------------------------------------
Doctoral Trainee • Vision: Science to Applications (VISTA)
Susan Crocker and John Hunkin Award in Fine Arts

On Mar 23, 2023, at 2:34 PM, David Ogborn ***@***.***> wrote:



Cool! A few notes about ways to do that without building Estuary:

-to try out changes on the fly, you can use Chrome's inspector (right-click anywhere and choose inspect), click on specific elements to display the style rules they are using, and then navigate through that to find the part near the bottom where it says :root or to other parts where the source comes from one of Estuary's custom stylesheets and make changes. This is useful for figuring out what you want quickly.

-when you know what you want, you can make a new custom stylesheet following the template of (for example) classic.css and then host it somewhere else on the web (for example, a github pages site).

-then you can use that theme by passing a parameter when you load Estuary (this feature has been there for a long time, but undocumented! :) :
https://estuary.mcmaster.ca?theme=https://dktr0.github.io/estuary-themes/test.css

-or you can use the new terminal command I just added in Estuary's terminal:
!theme "https://dktr0.github.io/estuary-themes/test.css"

I plan to eventually make references to custom themes a feature of ensembles instead of simply client-local settings, but this might be a little while coming.

Hope that helps! It'll sure be easier than building Estuary which can be a bit of a pain...

**Comment by opheliagame** [comment]
@dktr0 

I ran into the same issue after installing nix on macOS. 

The nix website mentions current build to be `2.34.6`. Which is possibly why it is failing on my machine too. 
https://nixos.org/download/

Wondering if there is any way to possibly resolve this? 

The reason I am trying to do a local build is to use some video files on the local network.

**Comment by dktr0** [comment]
@opheliagame I'm not able to look into this in any detail. I'm unclear from your message what version of Nix you are using, but you could try using 2.7.0 since it is reported as working in the thread above?

Although it may also have challenges (I haven't tried this), another route may be to run a CORS-compliant web server on/withing your local network, configured to only serve on the local network (possibly unnecessary if behind a typical firewall), and use it to serve the video files plus an Estuary reslist. Then - so the idea goes - you could still use estuary.mcmaster.ca in the usual way, but your reslist and video files would come from the firewalled local network?...

Oh, and there is another route, which is to not to use Nix at all, and instead use stack to build the estuary server (only) and then add it to a downloaded already built Estuary client from the github releases here. This is actually the workflow I use for estuary.mcmaster.ca (and, although not suitable for development work, it does tend to work better on more systems)!

**Comment by opheliagame** [comment]
@dktr0  

> another route may be to run a CORS-compliant web server

thanks! was able to make this work!! 
so now I can load images and video using the url at which the file is being served. 

since this is unrelated to the topic of this issue, will ask on discord is there is a way to load images and videos using reslist and not have to type the entire url.
